namespace HiringPipelineAPI.Models;

public class ErrorResponse
{
    /// <summary>
    /// A URI reference that identifies the problem type
    /// </summary>
    public string Type { get; set; } = string.Empty;

    /// <summary>
    /// A short, human-readable summary of the problem type
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// The HTTP status code generated by the origin server for this occurrence of the problem
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem
    /// </summary>
    public string Message { get; set; } = string.Empty;

    /// <summary>
    /// A unique identifier for this request, used for tracing and debugging
    /// </summary>
    public string TraceId { get; set; } = string.Empty;

    /// <summary>
    /// The timestamp when the error occurred
    /// </summary>
    public DateTime Timestamp { get; set; }

    /// <summary>
    /// The exception type name (only in development)
    /// </summary>
    public string? Exception { get; set; }

    /// <summary>
    /// The exception stack trace (only in development)
    /// </summary>
    public string? StackTrace { get; set; }

    /// <summary>
    /// Additional details about the error (only in development)
    /// </summary>
    public Dictionary<string, object>? Details { get; set; }
}
